---

# Repositorio EPEL
epel_repo: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'

# Paquete para Dive
dive_rpm: 'https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.rpm'

# Entradas /etc/hosts comunes a todas las máquinas
etc_hosts: [
       '10.150.0.10 master',
       '10.150.0.11 worker01',
       '10.150.0.12 worker02',
       '10.150.0.13 worker03',
       '10.150.0.200 nfs',
       ]

