---

# Instalaci贸n y arranque de docker

- name: configuraci贸n de repositorio de docker - GPG Key
  shell: "/usr/bin/curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg"
  become: yes

- name: configuraci贸n de repositorio de docker 
  shell: 'echo   "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  become: yes

- name: instalacion docker-ce
  shell: "/usr/bin/apt-get update; /usr/bin/apt-get install -y docker-ce docker-ce-cli containerd.io"
  become: yes

- name: configuraci贸n de arranque de docker
  systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
  become: yes

